{"name": "Test of failed attempt to create a repeating courier", "status": "passed", "description": "Negative test of the endpoint \"Создание курьера\" POST /api/v1/courier.Checks impossibility of creation of repeating courier", "start": 1717844771746, "stop": 1717844771886, "uuid": "589be60d-b949-4ae9-a0c7-862450c3c405", "historyId": "ca17d83a8867b941bdb05462eb6d457b", "testCaseId": "ca17d83a8867b941bdb05462eb6d457b", "fullName": "tests.test_courier_creation.TestCourierCreation#test_creation_repeating_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "DESKTOP-4KK18J8"}, {"name": "thread", "value": "44264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}