{"name": "Test of failed attempt to create a repeating courier", "status": "passed", "description": "Negative test of the endpoint \"Создание курьера\" POST /api/v1/courier.Checks impossibility of creation of repeating courier", "start": 1717848567055, "stop": 1717848567188, "uuid": "f79e4114-5ad2-4c9b-9288-a3adb99f8d60", "historyId": "ca17d83a8867b941bdb05462eb6d457b", "testCaseId": "ca17d83a8867b941bdb05462eb6d457b", "fullName": "tests.test_courier_creation.TestCourierCreation#test_creation_repeating_courier_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_creation"}, {"name": "subSuite", "value": "TestCourierCreation"}, {"name": "host", "value": "DESKTOP-4KK18J8"}, {"name": "thread", "value": "36728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_creation"}]}